inpackage: true
testonly: false
with-expecter: true
keeptree: false
log-level: warn
dir: "{{.InterfaceDir}}"
filename: "{{.InterfaceNameSnake}}_mock.go"
mockname: "Mocked{{.InterfaceName}}"
packages:
  github.com/travix/protoc-gen-gotf/extension:
    interfaces:
      Attribute:
      Block:
      Model:
      Provider:
      Synthesizer:
      TypeValue:
  github.com/travix/protoc-gen-gotf/gocode:
    interfaces:
      Writer:
