inpackage: true
testonly: false
with-expecter: true
keeptree: false
log-level: warn
packages:
  github.com/travix/protoc-gen-goterraform/extensions:
    interfaces:
      Block:
      Provider:
      Synthesizer:
      Attribute:
      TypeValue:
    config:
      dir: "extensions"
      filename: "{{.InterfaceNameSnake}}_mock.go"
      mockname: "Mocked{{.InterfaceName}}"
## used to generate /mocks for protoreflect
#  google.golang.org/protobuf/reflect/protoreflect:
#    interfaces:
#      FileDescriptor:
#      FieldDescriptor:
#      MapDescriptor:
#    config:
#      dir: "mocks"
#      filename: "{{.InterfaceNameSnake}}_mock.go"
#      mockname: "Mocked{{.InterfaceName}}"
#      inpackage: false
#      outpkg: "mocks"
