name: Setup Workflow job
description: Clone repository, setup Go, install Protoc, gocode code, download dependencies
runs:
  using: composite
  steps:
    - name: Clone
      uses: actions/checkout@v3
    - id: setup-go
      name: Setup GO
      uses: actions/setup-go@v4
      with:
          go-version: ^1
    - name: Install Protoc
      shell: bash
      run: |
        version=23.1
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${version}/protoc-${version}-linux-x86_64.zip
        unzip protoc-${version}-linux-x86_64.zip -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Generate
      shell: bash
      run: go generate ./...
    - name: Download dependencies
      if: steps.setup-go.outputs.cache-hit != 'true'
      shell: bash
      run: go get -t ./...
