name: Continuous Integration
on:
  push:
    branches:
    - "**"
    paths-ignore:
      - "**.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup repository
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Go fmt
        run: test -z $(gofmt -l .)
        shell: bash
      - name: Go fmt-diff
        if: failure()
        run: gofmt -e -d .
        shell: bash
      - name: Go vet
        if: success() || failure() # runs everytime except the job is cancelled
        run: go vet ./...
        shell: bash
      - name: Golangci lint
        uses: golangci/golangci-lint-action@v3
        if: success() || failure() # runs everytime except the job is cancelled
        with:
          skip-pkg-cache: true
          args: --timeout=1m

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup repository
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit test without race
        run: go test ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup repository
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: go build
