name: Continuous Integration
on:
  push:
    branches:
    - main
    paths-ignore:
      - "**.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup job
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
      - name: Go fmt
        run: test -z $(gofmt -l .)
        shell: bash
      - name: Go fmt-diff
        if: failure()
        run: gofmt -e -d .
        shell: bash
      - name: Go vet
        if: success() || failure() # runs everytime except the job is cancelled
        run: go vet ./...
        shell: bash
      - name: Golangci lint
        uses: golangci/golangci-lint-action@v3
        if: success() || failure() # runs everytime except the job is cancelled
        with:
          skip-pkg-cache: true
          args: --timeout=3s

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup job
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
      - name: Unit test without race
        run: go test ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup job
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
      - name: Build
        run: go build

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup job
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
      - name: Release CLI
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-setup-action@v1.18.0
        with:
          github_token: ${{ github.token }}
          buf_user: ${{ secrets.buf_user }}
          buf_api_token: ${{ secrets.buf_api_token }}
      - name: Release Protobuf
        run: buf push
        env:
          BUF_USERNAME: ${{ secrets.BUF_USERNAME }}
          BUF_PASSWORD: ${{ secrets.BUF_PASSWORD }}
