name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release ${{ github.ref_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup repository
        uses: travix/protoc-gen-gotf/.github/actions/setup-job@main
        with:
          buf_api_token: ${{ secrets.buf_api_token }}
          buf_user: ${{ vars.buf_user }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release CLI
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Protobuf
        run: buf push
